// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: toit/model/program.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Toit.Proto.Model {

  /// <summary>Holder for reflection information generated from toit/model/program.proto</summary>
  public static partial class ProgramReflection {

    #region Descriptor
    /// <summary>File descriptor for toit/model/program.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProgramReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chh0b2l0L21vZGVsL3Byb2dyYW0ucHJvdG8SCnRvaXQubW9kZWwaH2dvb2ds",
            "ZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8icQoGU291cmNlEgoKAmlkGAEg",
            "ASgMEi4KCmNyZWF0ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGlt",
            "ZXN0YW1wEhcKD29yZ2FuaXphdGlvbl9pZBgEIAEoDBISCgpjcmVhdG9yX2lk",
            "GAUgASgMIsoBCgdQcm9ncmFtEgoKAmlkGAEgASgMEgwKBG5hbWUYAiABKAkS",
            "EQoJdGVtcG9yYXJ5GAMgASgIEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wEhEKCXNvdXJjZV9pZBgFIAEoDBIiCgZz",
            "b3VyY2UYBiABKAsyEi50b2l0Lm1vZGVsLlNvdXJjZRIXCg9vcmdhbml6YXRp",
            "b25faWQYByABKAwSEgoKY3JlYXRvcl9pZBgIIAEoDCL/AQoLQ29tcGlsYXRp",
            "b24SCgoCaWQYASABKAwSCwoDc2RrGAIgASgJEhEKCWFyZ3VtZW50cxgDIAMo",
            "CRISCgpwcm9ncmFtX2lkGAQgASgMEiQKB3Byb2dyYW0YBSABKAsyEy50b2l0",
            "Lm1vZGVsLlByb2dyYW0SLQoGcmVzdWx0GAYgASgLMh0udG9pdC5tb2RlbC5D",
            "b21waWxhdGlvblJlc3VsdBIuCgpjcmVhdGVkX2F0GAcgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBIXCg9vcmdhbml6YXRpb25faWQYCCABKAwS",
            "EgoKY3JlYXRvcl9pZBgJIAEoDCKnAQoRQ29tcGlsYXRpb25SZXN1bHQSDQoF",
            "ZXJyb3IYASABKAkSFAoMc25hcHNob3Rfb3V0GAIgASgMEhQKDHNuYXBzaG90",
            "X2VychgDIAEoDBIZChFzbmFwc2hvdF9leGl0Y29kZRgEIAEoBRIRCglpbWFn",
            "ZV9vdXQYBSABKAwSEQoJaW1hZ2VfZXJyGAYgASgMEhYKDmltYWdlX2V4aXRj",
            "b2RlGAcgASgFIqQCCgNTREsSDAoEbmFtZRgBIAEoCRIPCgd2ZXJzaW9uGAIg",
            "ASgJEi4KCmNyZWF0ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGlt",
            "ZXN0YW1wEhIKCmNyZWF0ZWRfYnkYBCABKAkSLwoIc2V0dGluZ3MYBSADKAsy",
            "HS50b2l0Lm1vZGVsLlNESy5TZXR0aW5nc0VudHJ5Eg4KBm1vZGVscxgGIAMo",
            "CRI0Cg1yZWxlYXNlX2xldmVsGAcgASgOMh0udG9pdC5tb2RlbC5SZWxlYXNl",
            "TGV2ZWwuVHlwZRISCgpkZXByZWNhdGVkGAggASgIGi8KDVNldHRpbmdzRW50",
            "cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJmCgxSZWxlYXNl",
            "TGV2ZWwiVgoEVHlwZRILCgdVTktOT1dOEAASDAoIUkVMRUFTRUQQChIICgRC",
            "RVRBEBQSCQoFQUxQSEEQHhIICgRFREdFECgSCgoGTEFURVNUEDISCAoDQUxM",
            "EP8BQmMKGGlvLnRvaXQucHJvdG8udG9pdC5tb2RlbEIMUHJvZ3JhbVByb3Rv",
            "WiZnaXRodWIuY29tL3RvaXR3YXJlL2FwaS5naXQvdG9pdC9tb2RlbKoCEFRv",
            "aXQuUHJvdG8uTW9kZWxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.Source), global::Toit.Proto.Model.Source.Parser, new[]{ "Id", "CreatedAt", "OrganizationId", "CreatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.Program), global::Toit.Proto.Model.Program.Parser, new[]{ "Id", "Name", "Temporary", "CreatedAt", "SourceId", "Source", "OrganizationId", "CreatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.Compilation), global::Toit.Proto.Model.Compilation.Parser, new[]{ "Id", "Sdk", "Arguments", "ProgramId", "Program", "Result", "CreatedAt", "OrganizationId", "CreatorId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.CompilationResult), global::Toit.Proto.Model.CompilationResult.Parser, new[]{ "Error", "SnapshotOut", "SnapshotErr", "SnapshotExitcode", "ImageOut", "ImageErr", "ImageExitcode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.SDK), global::Toit.Proto.Model.SDK.Parser, new[]{ "Name", "Version", "CreatedAt", "CreatedBy", "Settings", "Models", "ReleaseLevel", "Deprecated" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Toit.Proto.Model.ReleaseLevel), global::Toit.Proto.Model.ReleaseLevel.Parser, null, null, new[]{ typeof(global::Toit.Proto.Model.ReleaseLevel.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Source : pb::IMessage<Source>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Source> _parser = new pb::MessageParser<Source>(() => new Source());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Source> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Source() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Source(Source other) : this() {
      id_ = other.id_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      organizationId_ = other.organizationId_;
      creatorId_ = other.creatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Source Clone() {
      return new Source(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private pb::ByteString id_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 4;
    private pb::ByteString organizationId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creator_id" field.</summary>
    public const int CreatorIdFieldNumber = 5;
    private pb::ByteString creatorId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString CreatorId {
      get { return creatorId_; }
      set {
        creatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Source);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Source other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (CreatorId != other.CreatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (CreatorId.Length != 0) hash ^= CreatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Id);
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CreatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Source other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.CreatorId.Length != 0) {
        CreatorId = other.CreatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 26: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 34: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 42: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 26: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 34: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 42: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Program : pb::IMessage<Program>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Program> _parser = new pb::MessageParser<Program>(() => new Program());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Program> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Program() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Program(Program other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      temporary_ = other.temporary_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      sourceId_ = other.sourceId_;
      source_ = other.source_ != null ? other.source_.Clone() : null;
      organizationId_ = other.organizationId_;
      creatorId_ = other.creatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Program Clone() {
      return new Program(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private pb::ByteString id_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "temporary" field.</summary>
    public const int TemporaryFieldNumber = 3;
    private bool temporary_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Temporary {
      get { return temporary_; }
      set {
        temporary_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "source_id" field.</summary>
    public const int SourceIdFieldNumber = 5;
    private pb::ByteString sourceId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SourceId {
      get { return sourceId_; }
      set {
        sourceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 6;
    private global::Toit.Proto.Model.Source source_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Toit.Proto.Model.Source Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 7;
    private pb::ByteString organizationId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creator_id" field.</summary>
    public const int CreatorIdFieldNumber = 8;
    private pb::ByteString creatorId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString CreatorId {
      get { return creatorId_; }
      set {
        creatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Program);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Program other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Temporary != other.Temporary) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (SourceId != other.SourceId) return false;
      if (!object.Equals(Source, other.Source)) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (CreatorId != other.CreatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Temporary != false) hash ^= Temporary.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (SourceId.Length != 0) hash ^= SourceId.GetHashCode();
      if (source_ != null) hash ^= Source.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (CreatorId.Length != 0) hash ^= CreatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Temporary != false) {
        output.WriteRawTag(24);
        output.WriteBool(Temporary);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CreatedAt);
      }
      if (SourceId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(SourceId);
      }
      if (source_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Source);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Temporary != false) {
        output.WriteRawTag(24);
        output.WriteBool(Temporary);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CreatedAt);
      }
      if (SourceId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(SourceId);
      }
      if (source_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Source);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Temporary != false) {
        size += 1 + 1;
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (SourceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SourceId);
      }
      if (source_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Source);
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CreatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Program other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Temporary != false) {
        Temporary = other.Temporary;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.SourceId.Length != 0) {
        SourceId = other.SourceId;
      }
      if (other.source_ != null) {
        if (source_ == null) {
          Source = new global::Toit.Proto.Model.Source();
        }
        Source.MergeFrom(other.Source);
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.CreatorId.Length != 0) {
        CreatorId = other.CreatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Temporary = input.ReadBool();
            break;
          }
          case 34: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 42: {
            SourceId = input.ReadBytes();
            break;
          }
          case 50: {
            if (source_ == null) {
              Source = new global::Toit.Proto.Model.Source();
            }
            input.ReadMessage(Source);
            break;
          }
          case 58: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 66: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Temporary = input.ReadBool();
            break;
          }
          case 34: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 42: {
            SourceId = input.ReadBytes();
            break;
          }
          case 50: {
            if (source_ == null) {
              Source = new global::Toit.Proto.Model.Source();
            }
            input.ReadMessage(Source);
            break;
          }
          case 58: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 66: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Compilation : pb::IMessage<Compilation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Compilation> _parser = new pb::MessageParser<Compilation>(() => new Compilation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Compilation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Compilation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Compilation(Compilation other) : this() {
      id_ = other.id_;
      sdk_ = other.sdk_;
      arguments_ = other.arguments_.Clone();
      programId_ = other.programId_;
      program_ = other.program_ != null ? other.program_.Clone() : null;
      result_ = other.result_ != null ? other.result_.Clone() : null;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      organizationId_ = other.organizationId_;
      creatorId_ = other.creatorId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Compilation Clone() {
      return new Compilation(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private pb::ByteString id_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sdk" field.</summary>
    public const int SdkFieldNumber = 2;
    private string sdk_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sdk {
      get { return sdk_; }
      set {
        sdk_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "arguments" field.</summary>
    public const int ArgumentsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_arguments_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> arguments_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Arguments {
      get { return arguments_; }
    }

    /// <summary>Field number for the "program_id" field.</summary>
    public const int ProgramIdFieldNumber = 4;
    private pb::ByteString programId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ProgramId {
      get { return programId_; }
      set {
        programId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "program" field.</summary>
    public const int ProgramFieldNumber = 5;
    private global::Toit.Proto.Model.Program program_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Toit.Proto.Model.Program Program {
      get { return program_; }
      set {
        program_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 6;
    private global::Toit.Proto.Model.CompilationResult result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Toit.Proto.Model.CompilationResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 8;
    private pb::ByteString organizationId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "creator_id" field.</summary>
    public const int CreatorIdFieldNumber = 9;
    private pb::ByteString creatorId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString CreatorId {
      get { return creatorId_; }
      set {
        creatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Compilation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Compilation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Sdk != other.Sdk) return false;
      if(!arguments_.Equals(other.arguments_)) return false;
      if (ProgramId != other.ProgramId) return false;
      if (!object.Equals(Program, other.Program)) return false;
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (CreatorId != other.CreatorId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Sdk.Length != 0) hash ^= Sdk.GetHashCode();
      hash ^= arguments_.GetHashCode();
      if (ProgramId.Length != 0) hash ^= ProgramId.GetHashCode();
      if (program_ != null) hash ^= Program.GetHashCode();
      if (result_ != null) hash ^= Result.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (CreatorId.Length != 0) hash ^= CreatorId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (Sdk.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Sdk);
      }
      arguments_.WriteTo(output, _repeated_arguments_codec);
      if (ProgramId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ProgramId);
      }
      if (program_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Program);
      }
      if (result_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Result);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Id);
      }
      if (Sdk.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Sdk);
      }
      arguments_.WriteTo(ref output, _repeated_arguments_codec);
      if (ProgramId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ProgramId);
      }
      if (program_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Program);
      }
      if (result_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Result);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(CreatorId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Id);
      }
      if (Sdk.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sdk);
      }
      size += arguments_.CalculateSize(_repeated_arguments_codec);
      if (ProgramId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProgramId);
      }
      if (program_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Program);
      }
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(OrganizationId);
      }
      if (CreatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CreatorId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Compilation other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Sdk.Length != 0) {
        Sdk = other.Sdk;
      }
      arguments_.Add(other.arguments_);
      if (other.ProgramId.Length != 0) {
        ProgramId = other.ProgramId;
      }
      if (other.program_ != null) {
        if (program_ == null) {
          Program = new global::Toit.Proto.Model.Program();
        }
        Program.MergeFrom(other.Program);
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Toit.Proto.Model.CompilationResult();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.CreatorId.Length != 0) {
        CreatorId = other.CreatorId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            Sdk = input.ReadString();
            break;
          }
          case 26: {
            arguments_.AddEntriesFrom(input, _repeated_arguments_codec);
            break;
          }
          case 34: {
            ProgramId = input.ReadBytes();
            break;
          }
          case 42: {
            if (program_ == null) {
              Program = new global::Toit.Proto.Model.Program();
            }
            input.ReadMessage(Program);
            break;
          }
          case 50: {
            if (result_ == null) {
              Result = new global::Toit.Proto.Model.CompilationResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 58: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 66: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 74: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadBytes();
            break;
          }
          case 18: {
            Sdk = input.ReadString();
            break;
          }
          case 26: {
            arguments_.AddEntriesFrom(ref input, _repeated_arguments_codec);
            break;
          }
          case 34: {
            ProgramId = input.ReadBytes();
            break;
          }
          case 42: {
            if (program_ == null) {
              Program = new global::Toit.Proto.Model.Program();
            }
            input.ReadMessage(Program);
            break;
          }
          case 50: {
            if (result_ == null) {
              Result = new global::Toit.Proto.Model.CompilationResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 58: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 66: {
            OrganizationId = input.ReadBytes();
            break;
          }
          case 74: {
            CreatorId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CompilationResult : pb::IMessage<CompilationResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CompilationResult> _parser = new pb::MessageParser<CompilationResult>(() => new CompilationResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CompilationResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompilationResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompilationResult(CompilationResult other) : this() {
      error_ = other.error_;
      snapshotOut_ = other.snapshotOut_;
      snapshotErr_ = other.snapshotErr_;
      snapshotExitcode_ = other.snapshotExitcode_;
      imageOut_ = other.imageOut_;
      imageErr_ = other.imageErr_;
      imageExitcode_ = other.imageExitcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompilationResult Clone() {
      return new CompilationResult(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "snapshot_out" field.</summary>
    public const int SnapshotOutFieldNumber = 2;
    private pb::ByteString snapshotOut_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SnapshotOut {
      get { return snapshotOut_; }
      set {
        snapshotOut_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "snapshot_err" field.</summary>
    public const int SnapshotErrFieldNumber = 3;
    private pb::ByteString snapshotErr_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SnapshotErr {
      get { return snapshotErr_; }
      set {
        snapshotErr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "snapshot_exitcode" field.</summary>
    public const int SnapshotExitcodeFieldNumber = 4;
    private int snapshotExitcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SnapshotExitcode {
      get { return snapshotExitcode_; }
      set {
        snapshotExitcode_ = value;
      }
    }

    /// <summary>Field number for the "image_out" field.</summary>
    public const int ImageOutFieldNumber = 5;
    private pb::ByteString imageOut_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ImageOut {
      get { return imageOut_; }
      set {
        imageOut_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image_err" field.</summary>
    public const int ImageErrFieldNumber = 6;
    private pb::ByteString imageErr_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ImageErr {
      get { return imageErr_; }
      set {
        imageErr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image_exitcode" field.</summary>
    public const int ImageExitcodeFieldNumber = 7;
    private int imageExitcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ImageExitcode {
      get { return imageExitcode_; }
      set {
        imageExitcode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CompilationResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CompilationResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      if (SnapshotOut != other.SnapshotOut) return false;
      if (SnapshotErr != other.SnapshotErr) return false;
      if (SnapshotExitcode != other.SnapshotExitcode) return false;
      if (ImageOut != other.ImageOut) return false;
      if (ImageErr != other.ImageErr) return false;
      if (ImageExitcode != other.ImageExitcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (SnapshotOut.Length != 0) hash ^= SnapshotOut.GetHashCode();
      if (SnapshotErr.Length != 0) hash ^= SnapshotErr.GetHashCode();
      if (SnapshotExitcode != 0) hash ^= SnapshotExitcode.GetHashCode();
      if (ImageOut.Length != 0) hash ^= ImageOut.GetHashCode();
      if (ImageErr.Length != 0) hash ^= ImageErr.GetHashCode();
      if (ImageExitcode != 0) hash ^= ImageExitcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Error.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Error);
      }
      if (SnapshotOut.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SnapshotOut);
      }
      if (SnapshotErr.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SnapshotErr);
      }
      if (SnapshotExitcode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SnapshotExitcode);
      }
      if (ImageOut.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ImageOut);
      }
      if (ImageErr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(ImageErr);
      }
      if (ImageExitcode != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ImageExitcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Error.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Error);
      }
      if (SnapshotOut.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(SnapshotOut);
      }
      if (SnapshotErr.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(SnapshotErr);
      }
      if (SnapshotExitcode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SnapshotExitcode);
      }
      if (ImageOut.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ImageOut);
      }
      if (ImageErr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(ImageErr);
      }
      if (ImageExitcode != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ImageExitcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (SnapshotOut.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SnapshotOut);
      }
      if (SnapshotErr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SnapshotErr);
      }
      if (SnapshotExitcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SnapshotExitcode);
      }
      if (ImageOut.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ImageOut);
      }
      if (ImageErr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ImageErr);
      }
      if (ImageExitcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ImageExitcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CompilationResult other) {
      if (other == null) {
        return;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.SnapshotOut.Length != 0) {
        SnapshotOut = other.SnapshotOut;
      }
      if (other.SnapshotErr.Length != 0) {
        SnapshotErr = other.SnapshotErr;
      }
      if (other.SnapshotExitcode != 0) {
        SnapshotExitcode = other.SnapshotExitcode;
      }
      if (other.ImageOut.Length != 0) {
        ImageOut = other.ImageOut;
      }
      if (other.ImageErr.Length != 0) {
        ImageErr = other.ImageErr;
      }
      if (other.ImageExitcode != 0) {
        ImageExitcode = other.ImageExitcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Error = input.ReadString();
            break;
          }
          case 18: {
            SnapshotOut = input.ReadBytes();
            break;
          }
          case 26: {
            SnapshotErr = input.ReadBytes();
            break;
          }
          case 32: {
            SnapshotExitcode = input.ReadInt32();
            break;
          }
          case 42: {
            ImageOut = input.ReadBytes();
            break;
          }
          case 50: {
            ImageErr = input.ReadBytes();
            break;
          }
          case 56: {
            ImageExitcode = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Error = input.ReadString();
            break;
          }
          case 18: {
            SnapshotOut = input.ReadBytes();
            break;
          }
          case 26: {
            SnapshotErr = input.ReadBytes();
            break;
          }
          case 32: {
            SnapshotExitcode = input.ReadInt32();
            break;
          }
          case 42: {
            ImageOut = input.ReadBytes();
            break;
          }
          case 50: {
            ImageErr = input.ReadBytes();
            break;
          }
          case 56: {
            ImageExitcode = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SDK : pb::IMessage<SDK>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SDK> _parser = new pb::MessageParser<SDK>(() => new SDK());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SDK> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDK() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDK(SDK other) : this() {
      name_ = other.name_;
      version_ = other.version_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      createdBy_ = other.createdBy_;
      settings_ = other.settings_.Clone();
      models_ = other.models_.Clone();
      releaseLevel_ = other.releaseLevel_;
      deprecated_ = other.deprecated_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SDK Clone() {
      return new SDK(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "created_by" field.</summary>
    public const int CreatedByFieldNumber = 4;
    private string createdBy_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CreatedBy {
      get { return createdBy_; }
      set {
        createdBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "settings" field.</summary>
    public const int SettingsFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_settings_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> settings_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Settings {
      get { return settings_; }
    }

    /// <summary>Field number for the "models" field.</summary>
    public const int ModelsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_models_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> models_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Models {
      get { return models_; }
    }

    /// <summary>Field number for the "release_level" field.</summary>
    public const int ReleaseLevelFieldNumber = 7;
    private global::Toit.Proto.Model.ReleaseLevel.Types.Type releaseLevel_ = global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Toit.Proto.Model.ReleaseLevel.Types.Type ReleaseLevel {
      get { return releaseLevel_; }
      set {
        releaseLevel_ = value;
      }
    }

    /// <summary>Field number for the "deprecated" field.</summary>
    public const int DeprecatedFieldNumber = 8;
    private bool deprecated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Deprecated {
      get { return deprecated_; }
      set {
        deprecated_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SDK);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SDK other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Version != other.Version) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (CreatedBy != other.CreatedBy) return false;
      if (!Settings.Equals(other.Settings)) return false;
      if(!models_.Equals(other.models_)) return false;
      if (ReleaseLevel != other.ReleaseLevel) return false;
      if (Deprecated != other.Deprecated) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (CreatedBy.Length != 0) hash ^= CreatedBy.GetHashCode();
      hash ^= Settings.GetHashCode();
      hash ^= models_.GetHashCode();
      if (ReleaseLevel != global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown) hash ^= ReleaseLevel.GetHashCode();
      if (Deprecated != false) hash ^= Deprecated.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Version);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatedAt);
      }
      if (CreatedBy.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CreatedBy);
      }
      settings_.WriteTo(output, _map_settings_codec);
      models_.WriteTo(output, _repeated_models_codec);
      if (ReleaseLevel != global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ReleaseLevel);
      }
      if (Deprecated != false) {
        output.WriteRawTag(64);
        output.WriteBool(Deprecated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Version);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CreatedAt);
      }
      if (CreatedBy.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CreatedBy);
      }
      settings_.WriteTo(ref output, _map_settings_codec);
      models_.WriteTo(ref output, _repeated_models_codec);
      if (ReleaseLevel != global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ReleaseLevel);
      }
      if (Deprecated != false) {
        output.WriteRawTag(64);
        output.WriteBool(Deprecated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (CreatedBy.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreatedBy);
      }
      size += settings_.CalculateSize(_map_settings_codec);
      size += models_.CalculateSize(_repeated_models_codec);
      if (ReleaseLevel != global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReleaseLevel);
      }
      if (Deprecated != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SDK other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.CreatedBy.Length != 0) {
        CreatedBy = other.CreatedBy;
      }
      settings_.Add(other.settings_);
      models_.Add(other.models_);
      if (other.ReleaseLevel != global::Toit.Proto.Model.ReleaseLevel.Types.Type.Unknown) {
        ReleaseLevel = other.ReleaseLevel;
      }
      if (other.Deprecated != false) {
        Deprecated = other.Deprecated;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Version = input.ReadString();
            break;
          }
          case 26: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 34: {
            CreatedBy = input.ReadString();
            break;
          }
          case 42: {
            settings_.AddEntriesFrom(input, _map_settings_codec);
            break;
          }
          case 50: {
            models_.AddEntriesFrom(input, _repeated_models_codec);
            break;
          }
          case 56: {
            ReleaseLevel = (global::Toit.Proto.Model.ReleaseLevel.Types.Type) input.ReadEnum();
            break;
          }
          case 64: {
            Deprecated = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Version = input.ReadString();
            break;
          }
          case 26: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 34: {
            CreatedBy = input.ReadString();
            break;
          }
          case 42: {
            settings_.AddEntriesFrom(ref input, _map_settings_codec);
            break;
          }
          case 50: {
            models_.AddEntriesFrom(ref input, _repeated_models_codec);
            break;
          }
          case 56: {
            ReleaseLevel = (global::Toit.Proto.Model.ReleaseLevel.Types.Type) input.ReadEnum();
            break;
          }
          case 64: {
            Deprecated = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReleaseLevel : pb::IMessage<ReleaseLevel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReleaseLevel> _parser = new pb::MessageParser<ReleaseLevel>(() => new ReleaseLevel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReleaseLevel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Toit.Proto.Model.ProgramReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLevel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLevel(ReleaseLevel other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLevel Clone() {
      return new ReleaseLevel(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReleaseLevel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReleaseLevel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReleaseLevel other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ReleaseLevel message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("RELEASED")] Released = 10,
        [pbr::OriginalName("BETA")] Beta = 20,
        [pbr::OriginalName("ALPHA")] Alpha = 30,
        [pbr::OriginalName("EDGE")] Edge = 40,
        [pbr::OriginalName("LATEST")] Latest = 50,
        [pbr::OriginalName("ALL")] All = 255,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
