# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from toit.api import simulator_pb2 as toit_dot_api_dot_simulator__pb2


class SimulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSimulator = channel.unary_unary(
                '/toit.api.SimulatorService/CreateSimulator',
                request_serializer=toit_dot_api_dot_simulator__pb2.CreateSimulatorRequest.SerializeToString,
                response_deserializer=toit_dot_api_dot_simulator__pb2.CreateSimulatorResponse.FromString,
                )
        self.RemoveSimulator = channel.unary_unary(
                '/toit.api.SimulatorService/RemoveSimulator',
                request_serializer=toit_dot_api_dot_simulator__pb2.RemoveSimulatorRequest.SerializeToString,
                response_deserializer=toit_dot_api_dot_simulator__pb2.RemoveSimulatorResponse.FromString,
                )
        self.ListSimulators = channel.unary_unary(
                '/toit.api.SimulatorService/ListSimulators',
                request_serializer=toit_dot_api_dot_simulator__pb2.ListSimulatorsRequest.SerializeToString,
                response_deserializer=toit_dot_api_dot_simulator__pb2.ListSimulatorsResponse.FromString,
                )
        self.CreateHardwareIdentity = channel.unary_unary(
                '/toit.api.SimulatorService/CreateHardwareIdentity',
                request_serializer=toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityRequest.SerializeToString,
                response_deserializer=toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityResponse.FromString,
                )


class SimulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSimulator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSimulator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSimulators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHardwareIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSimulator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSimulator,
                    request_deserializer=toit_dot_api_dot_simulator__pb2.CreateSimulatorRequest.FromString,
                    response_serializer=toit_dot_api_dot_simulator__pb2.CreateSimulatorResponse.SerializeToString,
            ),
            'RemoveSimulator': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSimulator,
                    request_deserializer=toit_dot_api_dot_simulator__pb2.RemoveSimulatorRequest.FromString,
                    response_serializer=toit_dot_api_dot_simulator__pb2.RemoveSimulatorResponse.SerializeToString,
            ),
            'ListSimulators': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSimulators,
                    request_deserializer=toit_dot_api_dot_simulator__pb2.ListSimulatorsRequest.FromString,
                    response_serializer=toit_dot_api_dot_simulator__pb2.ListSimulatorsResponse.SerializeToString,
            ),
            'CreateHardwareIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHardwareIdentity,
                    request_deserializer=toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityRequest.FromString,
                    response_serializer=toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'toit.api.SimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSimulator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/toit.api.SimulatorService/CreateSimulator',
            toit_dot_api_dot_simulator__pb2.CreateSimulatorRequest.SerializeToString,
            toit_dot_api_dot_simulator__pb2.CreateSimulatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveSimulator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/toit.api.SimulatorService/RemoveSimulator',
            toit_dot_api_dot_simulator__pb2.RemoveSimulatorRequest.SerializeToString,
            toit_dot_api_dot_simulator__pb2.RemoveSimulatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSimulators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/toit.api.SimulatorService/ListSimulators',
            toit_dot_api_dot_simulator__pb2.ListSimulatorsRequest.SerializeToString,
            toit_dot_api_dot_simulator__pb2.ListSimulatorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateHardwareIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/toit.api.SimulatorService/CreateHardwareIdentity',
            toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityRequest.SerializeToString,
            toit_dot_api_dot_simulator__pb2.CreateHardwareIdentityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
