name: CI

on:
  push:
    branches: [ ci-testing ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0
        
  node:
    needs: setup
    runs-on: ubuntu-latest

    steps:      

      - name: yarn install
        run: |
          cd node
          yarn install
        
      - name: Build protobuf
        run: |
          cd node
          make protobuf
          
  commit:
    needs: [setup, node]
    runs-on: ubuntu-latest
    steps:
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          message: ci commit
          branch: ci-testing

