name: CI

on:
  push:
    branches: [ ci-testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          node-directory: ./node
      
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: yarn install
        run: yarn install
        working-directory: ${{node-directory}}
        
      - name: Run protoc
        run: make protobuf
        working-directory: ${{node-directory}}
  
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          message: ci commit
          branch: ci-testing

