name: CI

on:
  push:
    branches: [ ci-test ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Run a one-line script
        run: echo Hello, world!
  
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          message: ci commit

