name: Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Build
        working-directory: ./java
        run: mvn -B package --file pom.xml

      - name: Add & Commit
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v5.1.0
        with:
          message: ci commit
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
