name: Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          server-id: sonatype-nexus-staging
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.DEVELOPERS_SIGN_KEY }}
          gpg-passphrase: DEVELOPERS_GPG_PASSPHRASE

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Update version in pom.xml (Release only)
        if: github.event_name == 'release'
        working-directory: ./java
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build
        working-directory: ./java
        run: mvn -B package --file pom.xml

      - name: Add & commit
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: Leon Gungadin Mogensen
          author_email: leon@toitware.com
          message: built java source files
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload jar to release (Release only)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: java/target/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Deploy jar (Release only)
        if: github.event_name == 'release'
        working-directory: ./java
        run: mvn -B deploy --file pom.xml
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          DEVELOPERS_GPG_PASSPHRASE: ${{ secrets.DEVELOPERS_SIGN_SECRET }}
