name: Nodejs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  nodejs:
    name: Build NodeJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Yarn install
        working-directory: ./node
        run: yarn install

      - name: Build protobuf
        working-directory: ./node
        run: make protobuf

      - name: Add & Commit
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: Leon Gungadin Mogensen
          author_email: leon@toitware.com
          message: built nodejs source files
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
