name: Nodejs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  nodejs:
    name: Build NodeJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Yarn install
        working-directory: ./node
        run: yarn install

      - name: Update version in package.json (Release only)
        if: github.event_name == 'release'
        working-directory: ./node
        run: yarn version --new-version $(echo ${{ github.event.release.tag_name }} | sed -e "s/v//gI") --no-git-tag-version

      - name: Build protobuf
        working-directory: ./node
        run: make protobuf

      - name: Add & Commit
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: Leon Gungadin Mogensen
          author_email: leon@toitware.com
          message: built nodejs source files
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npmjs.org (Release only)
        if: github.event_name == 'release'
        working-directory: ./node
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_LEON_ACCESS_TOKEN }}
          access: restricted
