name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0


      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'

      - name: Pip install
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build protobuf
        working-directory: ./python
        run: make protobuf

      - name: Add & Commit
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v5.1.0
        with:
          message: ci commit
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
